# Generated by Django 5.0 on 2023-12-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='is_admin',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
