# Generated by Django 5.0 on 2023-12-20 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ports', '0002_port_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='port',
            name='is_admin',
        ),
    ]
